name: Deploy logic apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
          
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az group create -l northeurope -n Sadhana-rg3-dev
            az deployment group create -g Sadhana-rg3-dev --template-file ./Project-logic-app/LogicApp.json --parameters ./Project-logic-app/LogicApp.parameters.json --parameters password=${{secrets.GREETING_SERVICE_BASIC_AUTH_PASSWORD}}